[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "trading_bot"
version = "0.1.0"
authors = [
    { name = "Rishikesh Wadkar" },
]
description = "Nifty Options Trading Bot"
requires-python = ">=3.8" 